In [1]:
import numpy
numpy.set_printoptions(legacy='1.13')

A = numpy.array(input().split(),float)

print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))

1.1 2.2 3.3 4.4
[ 1.  2.  3.  4.]
[ 2.  3.  4.  5.]
[ 1.  2.  3.  4.]
